# 内置常量

## False True None
## NotImplemented
## Ellipsis ...
## __debug__

In [2]:
# 1. True 和 False - 布尔类型的常量
print(True)  # 输出: True
print(False)  # 输出: False

# 尝试给 True 或 False 赋值会引发 SyntaxError
# True = 1  # 这行会报错: SyntaxError: cannot assign to True

# 布尔运算示例
print(5 > 3)  # 输出: True
print(5 == 3)  # 输出: False

True
False
True
False


In [ ]:
# 2. None - 表示空值或无值
result = print("Hello")  # print函数没有返回值
print(result)  # 输出: None

def greet(name=None):
    if name is None:
        return "Hello, stranger!"
    return f"Hello, {name}!"

print(greet())  # 输出: Hello, stranger!
print(greet("Alice"))  # 输出: Hello, Alice!


Hello
None
Hello, stranger!
Hello, Alice!


In [4]:
# 3. NotImplemented - 用于特殊方法表示操作未实现
class MyNumber:
    def __init__(self, value):
        self.value = value
    
    def __add__(self, other):
        if isinstance(other, MyNumber):
            return MyNumber(self.value + other.value)
        return NotImplemented  # 表示不支持与其他类型的加法

num1 = MyNumber(5)
num2 = MyNumber(3)
print((num1 + num2).value)  # 输出: 8

try:
    num1 + 3  # 会尝试调用 int.__radd__，如果也不支持则引发 TypeError
except TypeError as e:
    print(f"错误: {e}")  # 输出: 错误: unsupported operand type(s) for +: 'MyNumber' and 'int'

8
错误: unsupported operand type(s) for +: 'MyNumber' and 'int'


In [6]:
# 5. __debug__ - 调试标志
if __debug__:
    print("调试模式已启用")  # 默认情况下会输出
else:
    print("调试模式已禁用")  # 使用 -O 选项运行Python时输出

调试模式已启用


In [7]:
print(type(...))  # <class 'ellipsis'>
print(... is Ellipsis)  # True

<class 'ellipsis'>
True


In [11]:
import numpy as np

arr = np.random.rand(2, 3, 4, 5)

print(arr.shape)  # 输出: (2, 3, 4, 5)
print(arr)

# 使用 ... 简化切片
print(arr[1, ...].shape)  # (3, 4, 5) - 等同于 arr[1, :, :, :]
print(arr[..., 2].shape)  # (2, 3, 5) - 等同于 arr[:, :, :, 5]

print(arr[1, ...])
print(arr[..., 2])

(2, 3, 4, 5)
[[[[0.28016496 0.92015124 0.32222793 0.80106031 0.79115692]
   [0.46646377 0.78380682 0.52194572 0.41792753 0.41063801]
   [0.09378067 0.32797629 0.71068203 0.42882149 0.43346844]
   [0.8207264  0.74984151 0.92136226 0.54389297 0.98974605]]

  [[0.89085021 0.64120244 0.98589939 0.53688451 0.64129876]
   [0.08573237 0.3242133  0.94450291 0.04484802 0.24600785]
   [0.60908365 0.08950656 0.08397818 0.8707404  0.77165023]
   [0.60957501 0.66509471 0.37337862 0.19975322 0.0333253 ]]

  [[0.33531846 0.01129917 0.55799546 0.12786166 0.1595649 ]
   [0.57120095 0.59969184 0.43224796 0.04864599 0.9100295 ]
   [0.23448626 0.90803993 0.45424892 0.30358553 0.9220253 ]
   [0.53224336 0.02559852 0.96636219 0.75468683 0.96123082]]]


 [[[0.74381975 0.38531107 0.69122742 0.87946005 0.89627642]
   [0.63213474 0.63854832 0.36468183 0.01940612 0.1125995 ]
   [0.82779931 0.33452399 0.76065609 0.87793385 0.93057085]
   [0.51778728 0.2692466  0.8524456  0.09732358 0.88385094]]

  [[0.34107816 0.